// Code generated by goctl. DO NOT EDIT.

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	eventFieldNames          = builder.RawFieldNames(&Event{})
	eventRows                = strings.Join(eventFieldNames, ",")
	eventRowsExpectAutoSet   = strings.Join(stringx.Remove(eventFieldNames, "`id`", "`create_at`", "`created_at`", "`create_time`", "`update_at`", "`updated_at`", "`update_time`"), ",")
	eventRowsWithPlaceHolder = strings.Join(stringx.Remove(eventFieldNames, "`id`", "`create_at`", "`created_at`", "`create_time`", "`update_at`", "`updated_at`", "`update_time`"), "=?,") + "=?"
)

type (
	eventModel interface {
		Insert(ctx context.Context, data *Event) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*Event, error)
		Update(ctx context.Context, data *Event) error
		Delete(ctx context.Context, id int64) error
	}

	defaultEventModel struct {
		conn  sqlx.SqlConn
		table string
	}

	Event struct {
		Id         int64     `db:"id"`          // 主键id
		Kind       string    `db:"kind"`        // 资源类型
		Namespace  string    `db:"namespace"`   // 名称空间
		Rtype      string    `db:"rtype"`       // 类型
		Reason     string    `db:"reason"`      // 原因
		Message    string    `db:"message"`     // 消息
		EventTime  time.Time `db:"eventTime"`   // 时间
		Cluster    string    `db:"cluster"`     // 集群名称
		CreateTime time.Time `db:"create_time"` // 创建时间
		Name       string    `db:"name"`
	}
)

func newEventModel(conn sqlx.SqlConn) *defaultEventModel {
	return &defaultEventModel{
		conn:  conn,
		table: "`event`",
	}
}

func (m *defaultEventModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultEventModel) FindOne(ctx context.Context, id int64) (*Event, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", eventRows, m.table)
	var resp Event
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultEventModel) Insert(ctx context.Context, data *Event) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?)", m.table, eventRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.Kind, data.Namespace, data.Rtype, data.Reason, data.Message, data.EventTime, data.Cluster, data.Name)
	return ret, err
}

func (m *defaultEventModel) Update(ctx context.Context, data *Event) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, eventRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.Kind, data.Namespace, data.Rtype, data.Reason, data.Message, data.EventTime, data.Cluster, data.Name, data.Id)
	return err
}

func (m *defaultEventModel) tableName() string {
	return m.table
}
