// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"server/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/pods",
				Handler: GetPodListHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/services",
				Handler: GetServiceistHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/k8s"),
	)
}
