// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"server/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/pods",
				Handler: GetPodListHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/pod/detail",
				Handler: GetPodDetailHandler(serverCtx),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/pod/del",
				Handler: DeletePodHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/pod/update",
				Handler: UpdatePodHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/pod/container",
				Handler: GetPodContainersHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/pod/log",
				Handler: GetPodLogHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/services",
				Handler: GetServiceListHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/k8s"),
	)
}
