// Code generated by goctl. DO NOT EDIT.
package types

type GetPodListRequest struct {
	Cluster    string `json:"cluster"`
	Namespace  string `json:"namespace"`
	FilterName string `json:"filterName"`
	Page       int    `json:"page"`
	Limit      int    `json:"limit"`
}

type GetPodListResponse struct {
	Code    string `json:"code"`
	Message string `json:"message"`
	Data    Pods   `json:"data"`
}

type Pods struct {
	Total   int         `json:"total"`
	PodList interface{} `json:"podList"`
}

type GetPodDetailRequest struct {
	Cluster   string `json:"cluster"`
	Namespace string `json:"namespace"`
	PodName   string `json:"podName"`
}

type GetPodDetailResponse struct {
	Code    string      `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data"`
}

type DeletePodRequest struct {
	Cluster   string `json:"cluster"`
	Namespace string `json:"namespace"`
	PodName   string `json:"podName"`
}

type DeletePodResponse struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}

type UpdatePodRequest struct {
	Cluster   string `json:"cluster"`
	Namespace string `json:"namespace"`
	Content   string `json:"content"`
}

type UpdatePodResponse struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}

type GetPodContainersRequest struct {
	Cluster   string `json:"cluster"`
	Namespace string `json:"namespace"`
	PodName   string `json:"podName"`
}

type GetPodContainersResponse struct {
	Code       string   `json:"code"`
	Message    string   `json:"message"`
	Containers []string `json:"containers"`
}

type GetPodLogRequest struct {
	Cluster       string `json:"cluster"`
	Namespace     string `json:"namespace"`
	PodName       string `json:"podName"`
	ContainerName string `json:"containerName"`
}

type GetPodLogResponse struct {
	Code    string `json:"code"`
	Message string `json:"message"`
	Log     string `json:"log"`
}

type GetServiceListRequest struct {
	Cluster    string `json:"cluster"`
	Namespace  string `json:"namespace"`
	FilterName string `json:"filterName"`
	Page       int    `json:"page"`
	Limit      int    `json:"limit"`
}

type GetServiceListResponse struct {
	Code    string   `json:"code"`
	Message string   `json:"message"`
	Data    Services `json:"data"`
}

type Services struct {
	Total       int         `json:"total"`
	ServiceList interface{} `json:"serviceList"`
}
