// Code generated by goctl. DO NOT EDIT.
package types

type GetPodListRequest struct {
	Cluster    string `json:"cluster"`
	Namespace  string `json:"namespace"`
	FilterName string `json:"filterName"`
	Page       int    `json:"page"`
	Limit      int    `json:"limit"`
}

type GetPodListResponse struct {
	Code string `json:"message"`
	Data Pods   `json:"data"`
}

type Pods struct {
	Total   int         `json:"total"`
	PodList interface{} `json:"podList"`
}

type GetServiceistRequest struct {
	Cluster    string `json:"cluster"`
	Namespace  string `json:"namespace"`
	FilterName string `json:"filterName"`
	Page       int    `json:"page"`
	Limit      int    `json:"limit"`
}

type GetServiceistResponse struct {
	Code string   `json:"message"`
	Data Services `json:"data"`
}

type Services struct {
	Total       int         `json:"total"`
	ServiceList interface{} `json:"serviceList"`
}
